//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazyLoad_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        public int id_almacen { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> isactive { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
